# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da5a4214897aac63ceb5268ee9898a5a98e5dea297ac1ace3464218dc4a5a1e6ddece6eee4b8f64491f8cbe283b5c7e5024091def0759f830f8997c70c2cd2fa

test:
  secret_key_base: 46153ff4f7cdb28a1629af25748a4abe3944e45b3482c49894cc85f58372cb96c744c3ad2ccdc6c81ecfd728b2382eb87ae845e5f20962255c243192e4cf2b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
